# Generated by Django 5.1.3 on 2024-11-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
    ]
