# Generated by Django 5.0.3 on 2024-03-19 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordernew', '0001_initial'),
        ('product', '0003_product_created_at_product_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_productsnew', to='ordernew.ordernew')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_productsnew', to='product.product')),
            ],
        ),
    ]
